[Appearance]
color_scheme_path=~/.local/share/color-schemes/Matugen.colors
custom_palette=true
icon_theme=Papirus
standard_dialogs=default
style=kvantum

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x6\x90\0\0\0\x8d\0\0\xe\x1\0\0\x4\x81\0\0\x6\x90\0\0\0\x8d\0\0\xe\xf\0\0\x4\xc4\0\0\0\0\x2\0\0\0\a\x80\0\0\x6\x90\0\0\0\x8d\0\0\xe\x1\0\0\x4\x81)
