cursor #191d17
cursor_text_color #43483f

foreground            #191d17
background            #f8fbf0
selection_foreground  #ffffff
selection_background  #bbcbb1
url_color             #416835

active_tab_foreground   #121f0e
active_tab_background   #d7e8cc
inactive_tab_foreground #121f0e
inactive_tab_background #d7e8cc

# black
color0   #f8fbf0
color8   #73796e

# red
color1   #ba1a1a
color9 #D20F39

# green
color2  #40A02B
color10 #40A02B

# yellow
color3  #DF8E1D
color11 #DF8E1D

# blue
color4  #1E66F5
color12 #1E66F5

# magenta
color5  #EA76CB
color13 #EA76CB

# cyan
color6  #179299
color14 #179299

# white
color7  #ACB0BE
color15 #BCC0CC