cursor            #191d17
cursor_text_color #43483f

foreground           #191d17
background           #f8fbf0
selection_foreground #ffffff
selection_background #bbcbb1
url_color            #416835

active_tab_foreground   #121f0e
active_tab_background   #d7e8cc
inactive_tab_foreground #121f0e
inactive_tab_background #d7e8cc

color0      #FDFFFC
color1		#34AB10
color2		#B06B0B
color3		#398F0B
color4		#AA2F00
color5		#523002
color6		#023512
color7		#0E2013
color8		#929B8F
color9		#46D214
color10		#D8820C
color11		#41AB0C
color12		#E94506
color13		#6D4003
color14		#034719
color15		#050B06
