$backgroundAlpha = rgba(f8fbf0aa)


   $foreground = rgba(f8fbf0ff)





$background = rgba(f8fbf0ff)

$error = rgba(ba1a1aff)

$error_container = rgba(ffdad6ff)

$inverse_on_surface = rgba(eff2e8ff)

$inverse_primary = rgba(a6d394ff)

$inverse_surface = rgba(2e322bff)

$on_background = rgba(191d17ff)

$on_error = rgba(ffffffff)

$on_error_container = rgba(410002ff)

$on_primary = rgba(ffffffff)

$on_primary_container = rgba(022100ff)

$on_primary_fixed = rgba(022100ff)

$on_primary_fixed_variant = rgba(2a4f1fff)

$on_secondary = rgba(ffffffff)

$on_secondary_container = rgba(121f0eff)

$on_secondary_fixed = rgba(121f0eff)

$on_secondary_fixed_variant = rgba(3d4b37ff)

$on_surface = rgba(191d17ff)

$on_surface_variant = rgba(43483fff)

$on_tertiary = rgba(ffffffff)

$on_tertiary_container = rgba(002021ff)

$on_tertiary_fixed = rgba(002021ff)

$on_tertiary_fixed_variant = rgba(1e4e50ff)

$outline = rgba(73796eff)

$outline_variant = rgba(c3c8bcff)

$primary = rgba(416835ff)

$primary_container = rgba(c1efafff)

$primary_fixed = rgba(c1efafff)

$primary_fixed_dim = rgba(a6d394ff)

$scrim = rgba(000000ff)

$secondary = rgba(54634dff)

$secondary_container = rgba(d7e8ccff)

$secondary_fixed = rgba(d7e8ccff)

$secondary_fixed_dim = rgba(bbcbb1ff)

$shadow = rgba(000000ff)

$source_color = rgba(568248ff)

$surface = rgba(f8fbf0ff)

$surface_bright = rgba(f8fbf0ff)

$surface_container = rgba(ecefe5ff)

$surface_container_high = rgba(e6e9dfff)

$surface_container_highest = rgba(e1e4daff)

$surface_container_low = rgba(f2f5ebff)

$surface_container_lowest = rgba(ffffffff)

$surface_dim = rgba(d8dbd1ff)

$surface_tint = rgba(416835ff)

$surface_variant = rgba(dfe4d7ff)

$tertiary = rgba(386668ff)

$tertiary_container = rgba(bcebeeff)

$tertiary_fixed = rgba(bcebeeff)

$tertiary_fixed_dim = rgba(a0cfd1ff)


