# You can find more wallpapers in ~/.config/mimic/wallpapers/
# Run ~/.config/hypr/reload-hyprpaper.sh after changing your wallpaper
preload = $HOME/.config/mimic/assets/blank.png
wallpaper = ,$HOME/.config/mimic/assets/blank.png
splash = false
