exec-once = m-listeners --startall
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# exec-once = systemctl --user start hyprpolkitagent
exec-once = m-restart-waybar
exec-once = m-theme-wallpaper-restore
exec-once = swaync
exec-once = hypridle
exec-once = wl-paste --watch cliphist store
exec-once = hyprpm reload
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
