plugin {
    hyprbars {
        bar_height = 20
        bar_color = $background
        # hyprbars-button = $surface_container_highest, 200, , hyprctl dispatch killactive
        hyprbars-button = $background, 200, , hyprctl dispatch killactive
        on_double_click = hyprctl dispatch fullscreen 1
        bar_title_enabled = false
        bar_precedence_over_border = true
        bar_padding = 0
        bar_button_padding = 0
        icon_on_hover = false
        bar_blur = true
    }
    overview {
        disableGestures = true
        affectStrut = false
    }
}