# Path to oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="dst"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

HIST_STAMPS="yyyy-mm-dd"
setopt EXTENDED_HISTORY

plugins=(git sudo encode64 copypath zsh-autosuggestions zsh-syntax-highlighting dirhistory jsontools zsh-history-substring-search fd)

source $ZSH/oh-my-zsh.sh

# User configuration
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down

alias ls="eza"
alias ll="eza -alhg"
alias tree="eza --tree"
alias pipes="$HOME/.local/bin/pipes.sh"

SILICON_BASE="silicon --no-window-controls --no-line-number  --pad-horiz 0 --pad-vert 0 --theme \"Catppuccin-macchiato\" --shadow-offset-x 0 --shadow-offset-y 0 --shadow-blur-radius 0"
alias sil="$SILICON_BASE -o"
alias sil-c="$SILICON_BASE --from-clipboard -o"

export PATH=$PATH:/home/ivankarpov/.spicetify
export PATH=$PATH:/home/ivankarpov/.cargo/bin
